#%RAML 0.8
---
title: TAS positionOpenings
baseUri: http://talentappstore.com/{version}
version: v1

resourceTypes: !include core.include.raml

/positionOpenings:
  description: PositionOpenings (HR-XML terminology) are openings of a specific position for recruitment.
  type:
    tasCollection:
      defaultFieldsList: id,kind,items/blah
      maxLimit: 30
      sortableFields: id,name,and all user fields
      filterCapabilities: |
        simple comparisons on the id field must be supported, e.g.:
        <ul>
        <li>id = 20
        <li>id > 10
        <li>id < 10
        </ul>
  get:
    description: Get a list of positionOpenings
    responses:
      200:
        body:
          application/json:
            schema: !include ../schemas/positionOpenings.json
            example: !include ../examples/positionOpenings.json
  /{id}:
    type:
      tasItem:


      